apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: wordpressvolume
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        ports:
        - containerPort: 80
        env: #IMPORTANT: no cal crear un phpmyadmin-secret, ja que podem reutilitzar
        #el mateix arxiu secret per a la bbdd i per al phpmyadmin!!!
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: maria-secret 
              key: maria-username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: maria-secret
              key: maria-password
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: maria-secret
              key: maria-password
        - name: PMA_HOST #Nom del PC (servei en aquest cas, que es maria-service) on es troba la BBDD.
          valueFrom: 
            configMapKeyRef: #OJO! No és secretKeyRef en aquest cas!
              name: maria-configmap #El name que hem posat a les metadades del configmap
              key: host #És la clau que farem servir al configmap
---
apiVersion: v1
kind: Service
metadata:
 name: phpmyadmin-service
 namespace: wordpressvolume
spec:
 selector:
   app: phpmyadmin #IMPORTANT! Ha de quadrar amb el label del Deployment!
 type: LoadBalancer #= servei extern, OJO! A l’alçada de “selector”!!!
 ports:
   - protocol: TCP
     port: 80 #Port del servei de phpmyadmin (amb apache 80/443...)
     targetPort: 80 #Port exposat, ha de quadrar amb el containerPort de més amunt
     nodePort: 30000 #min 30000, és el port que exposem externament
