apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress-deploy
 namespace: wordpressvolume
 labels:
   app: wordpress
spec:
 replicas: 1
 selector:
   matchLabels:
     app: wordpress
 template:
   metadata:
     labels:
       app: wordpress
   spec:
     containers:
     - name: wordpress
       image: wordpress
       ports:
       - containerPort: 80
       env: #Obligatori només un password, no cal ni user ni bbdd. A més les envvars es poden dir de diferents maneres, MYSQL_ROOT_PASSWORD també pot ser.
       - name: WORDPRESS_DB_USER
         valueFrom:
          secretKeyRef:
            name: maria-secret #El nom que hem posat a les metadades del secret
            key: maria-username #El valor que li hem donat
       - name: WORDPRESS_DB_PASSWORD
         valueFrom:
          secretKeyRef:
            name: maria-secret #El nom que hem posat a les metadades del secret
            key: maria-password #El valor que li hem donat
       - name: WORDPRESS_DB_HOST #Nom del PC on es troba la BBDD. En el cas de Kubernetes ha de ser el nom del servei del pod on es troba la bbdd (maria-service).
         valueFrom:
          configMapKeyRef: #OJO! No és secretKeyRef en aquest cas!
            name: maria-configmap #El name que hem posat a les metadades del configmap
            key: host #És la clau que farem servir al configmap
       - name: WORDPRESS_DB_NAME
         valueFrom:
          configMapKeyRef: #OJO! No és secretKeyRef en aquest cas!
            name: maria-configmap #El name que hem posat a les metadades del configmap
            key: nombbdd #És la clau que farem servir al configmap
       volumeMounts:
        - name: dadeswordpress #Ha de coincidir amb el de sota
          mountPath: /var/www/html #Directori on wp guarda les dades
     volumes:
       - name: dadeswordpress #Ha de coincidir amb el de sobre
         persistentVolumeClaim:
           claimName: wordpress-pvc #Ha de coincidir amb el PVC creat
---
apiVersion: v1
kind: Service
metadata:
 name: wordpress-service
 namespace: wordpressvolume
spec:
 selector:
   app: wordpress #IMPORTANT! Ha de quadrar amb el label del Deployment!
 type: LoadBalancer #= servei extern, OJO! A l’alçada de “selector”!!!
 ports:
   - protocol: TCP
     port: 80 #Port del servei de wordpress (amb apache 80/443...)
     targetPort: 80 #Port exposat, ha de quadrar amb el containerPort de més amunt
     nodePort: 30002 #min 30000, és el port que exposem externament
