apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv #Els PV NO han de tenir namespace!
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #Permet que només un node accedeixi al disc a la vegada
  persistentVolumeReclaimPolicy: Retain #Política de recuperació (?)
  local:
    path: /mnt/dades #Directori on hem muntat el disc de Dades
  nodeAffinity: #Hem de dir en quin node muntem el PV
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8swork1 #Nom del node on es monta el PVC
