apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap #Coincidint amb el nom del Deployment (veure variables d'entorn)
data:
  database_url: mongodb-service #és com el host on accedir a la BBDD. La connexió es faria a nivell de comandes amb mongosh “mongodb://usuari:password@mongodb-service:27017/"
